### PR TITLE
Sync main -> feature_sample_flattening

### PR DESCRIPTION
**Pull request by MrCreosote**

### CODE REVIEW

**Review by Tianhao-Gu — APPROVED** [review]
👍

**Comment by MrCreosote** [comment]
@Tianhao-Gu One test has failed multiple times in a row with the error `ValueError: Download Failed for GCF_000979375.1 after 3 attempts!`. The test is `test_download_genome_file` which [hasn't changed in 6 months](https://github.com/kbase/collections/blame/9ba47c0cb0776d0a7fdd78651c66a3cc65d7e8bf/test/src/loaders/ncbi_downloader/gtdb_test.py#L86) and [neither has the code under test](https://github.com/kbase/collections/blame/9ba47c0cb0776d0a7fdd78651c66a3cc65d7e8bf/src/loaders/ncbi_downloader/ncbi_downloader_helper.py#L14). My guess is that there's something wrong with NCBI right now rather than a problem with the code and we should probably just merge and see if the problem resolves later. If not we'll have to investigate further

**Comment by Tianhao-Gu** [comment]
> @Tianhao-Gu One test has failed multiple times in a row with the error `ValueError: Download Failed for GCF_000979375.1 after 3 attempts!`. The test is `test_download_genome_file` which [hasn't changed in 6 months](https://github.com/kbase/collections/blame/9ba47c0cb0776d0a7fdd78651c66a3cc65d7e8bf/test/src/loaders/ncbi_downloader/gtdb_test.py#L86) and [neither has the code under test](https://github.com/kbase/collections/blame/9ba47c0cb0776d0a7fdd78651c66a3cc65d7e8bf/src/loaders/ncbi_downloader/ncbi_downloader_helper.py#L14). My guess is that there's something wrong with NCBI right now rather than a problem with the code and we should probably just merge and see if the problem resolves later. If not we'll have to investigate further

noted. We can merge this PR now. Tests locally all passed too.

**Comment by MrCreosote** [comment]
> Tests locally all passed too.

Hmm, I wonder if NCBI started blocking GHA

**Comment by MrCreosote** [comment]
No, it fails locally for me too: 
```
E           ValueError: Download Failed for GCF_000979375.1 after 3 attempts!

src/loaders/ncbi_downloader/ncbi_downloader_helper.py:61: ValueError
----------------------------- Captured stdout call -----------------------------
Error:
[Errno -2] Name or service not known
Debugging info: ftputil 5.0.4, Python 3.11.3 (linux)
from attempt 1.
Trying to rerun.
Error:
[Errno -2] Name or service not known
Debugging info: ftputil 5.0.4, Python 3.11.3 (linux)
from attempt 2.
Trying to rerun.
Error:
[Errno -2] Name or service not known
Debugging info: ftputil 5.0.4, Python 3.11.3 (linux)
from attempt 3.
Trying to rerun.
```

**Comment by MrCreosote** [comment]
NCBI seems to be hosed
image

**Pull request merged**
