### PR TITLE
RE2022-328: using upload_result

### PR DESCRIPTION
**Pull request by Tianhao-Gu**

### CODE REVIEW

**Review by MrCreosote — COMMENTED** [review]
@Xiangs18 should take a look at this as well

**Review by MrCreosote — COMMENTED** [review]
LGTM but @Xiangs18 should review

**Comment by Xiangs18** [comment]
we are missing return type hints for functions that have @proprty. De we need to include them in the future PR?

**Comment by Tianhao-Gu** [comment]
> we are missing return type hints for functions that have @Proprty in upload_result.py. De we need to include them in the future PR?

added them.

**Review by Xiangs18 — APPROVED** [review]
LGTM!

**Pull request merged**
