### PR TITLE
RE2022-300: add display name and category for genome attrib

### PR DESCRIPTION
**Pull request by Tianhao-Gu**
example genome_attribs_meta:
```
{"columns": [{"key": "fastani_af", "type": "float", "filter_strategy": null, "display_name": "FastANI AF", "category": "Other", "description": null, "min_value": 0.76, "max_value": 0.76, "enum_values": null}, {"key": "Completeness", "type": "float", "filter_strategy": null, "display_name": "CheckM Completeness", "category": "Quality", "description": null, "min_value": 76.76, "max_value": 98.07, "enum_values": null}, {"key": "fastani_reference", "type": "string", "filter_strategy": "identity", "display_name": "FastANI Reference", "category": "Other", "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "closest_placement_reference", "type": "string", "filter_strategy": "identity", "display_name": "Closest Placement Reference", "category": "Other", "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "user_genome", "type": "string", "filter_strategy": "identity", "display_name": "User Genome", "category": "Other", "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "_mtchsel", "type": "string", "filter_strategy": "identity", "display_name": null, "category": null, "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "classification_method", "type": "string", "filter_strategy": "fulltext", "display_name": "Classification Method", "category": "Taxonomy", "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "fastani_taxonomy", "type": "string", "filter_strategy": "fulltext", "display_name": "FastANI Taxonomy", "category": "Other", "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "kbase_display_name", "type": "string", "filter_strategy": "ngram", "display_name": "KBase Name", "category": "Identifiers", "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "closest_placement_ani", "type": "float", "filter_strategy": null, "display_name": "Closest Placement ANI", "category": "Other", "description": null, "min_value": 76.9, "max_value": 96.85, "enum_values": null}, {"key": "fastani_ani", "type": "float", "filter_strategy": null, "display_name": "FastANI ANI", "category": "Other", "description": null, "min_value": 96.85, "max_value": 96.85, "enum_values": null}, {"key": "closest_placement_radius", "type": "float", "filter_strategy": null, "display_name": "Closest Placement Radius", "category": "Other", "description": null, "min_value": 95.0, "max_value": 95.0, "enum_values": null}, {"key": "load_ver", "type": "string", "filter_strategy": "identity", "display_name": null, "category": null, "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "classification", "type": "string", "filter_strategy": "ngram", "display_name": "Classification", "category": "Taxonomy", "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "red_value", "type": "string", "filter_strategy": "fulltext", "display_name": "Red Value", "category": "Other", "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "kbase_id", "type": "string", "filter_strategy": "identity", "display_name": "KBase ID", "category": "Identifiers", "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "Contamination", "type": "float", "filter_strategy": null, "display_name": "CheckM Contamination", "category": "Quality", "description": null, "min_value": 0.05, "max_value": 2.3, "enum_values": null}, {"key": "pplacer_taxonomy", "type": "string", "filter_strategy": "fulltext", "display_name": "pplacer Taxonomy", "category": "Other", "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "note", "type": "string", "filter_strategy": "fulltext", "display_name": "Note", "category": "Other", "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "coll", "type": "string", "filter_strategy": "identity", "display_name": null, "category": null, "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "closest_placement_af", "type": "float", "filter_strategy": null, "display_name": "Closest Placement AF", "category": "Other", "description": null, "min_value": 0.093, "max_value": 0.84, "enum_values": null}, {"key": "warnings", "type": "string", "filter_strategy": "fulltext", "display_name": "Warnings", "category": "Other", "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "kbase_sample_id", "type": "string", "filter_strategy": "identity", "display_name": "KBase Sample ID", "category": "Identifiers", "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "other_related_references(genome_id,species_name,radius,ANI,AF)", "type": "string", "filter_strategy": "fulltext", "display_name": "Other Related References", "category": "Other", "description": null, "min_value": null, "max_value": null, "enum_values": null}, {"key": "fastani_reference_radius", "type": "float", "filter_strategy": null, "display_name": "FastANI Reference Radius", "category": "Other", "description": null, "min_value": 95.0, "max_value": 95.0, "enum_values": null}, {"key": "msa_percent", "type": "float", "filter_strategy": null, "display_name": "MSA Percent", "category": "Other", "description": null, "min_value": 68.52, "max_value": 95.23, "enum_values": null}, {"key": "translation_table", "type": "int", "filter_strategy": null, "display_name": "Translation Table", "category": "Other", "description": null, "min_value": 11, "max_value": 11, "enum_values": null}], "count": 5, "_key": "8b838895201f80d818a1e3325cede938", "coll": "GROW", "load_ver": "tian_test_taskfarmer"}
```

### CODE REVIEW

**Comment by MrCreosote** [comment]
You'll need to add them to the models as well so they're documented in the openapi docs (and may even be necessary for them to return in the api, not sure about that

**Comment by MrCreosote** [comment]
No description placeholder?

**Comment by Tianhao-Gu** [comment]
> You'll need to add them to the models as well so they're documented in the openapi docs (and may even be necessary for them to return in the api, not sure about that

are you referring to the `AttributesColumnSpec` model? It will be included in the next PRs. Didn't include the changes here to avoid potential confusion for Cody. 
https://github.com/kbase/collections/blob/main/src/common/product_models/columnar_attribs_common_models.py#L52

**Comment by Tianhao-Gu** [comment]
> No description placeholder?

No description in the google doc yet (not in road map neither). I don't think we need a placeholder in the yaml file yet.

**Comment by MrCreosote** [comment]
> are you referring to the AttributesColumnSpec model? It will be included in the next PRs
Fair enough

**Comment by MrCreosote** [comment]
> No description in the google doc yet (not in road map neither). I don't think we need a placeholder in the yaml file yet.

It is in the roadmap, although there's a question mark by it. But based on the discussion in the standup we'll go ahead with the placeholder in the yaml docs

**Comment by Tianhao-Gu** [comment]
> > No description placeholder?
> 
> No description in the google doc yet (not in road map neither). I don't think we need a placeholder in the yaml file yet.

added place holder for description as discussed in standup.

**Review by MrCreosote — COMMENTED** [review]
LGTM. I'm relying on Cody to confirm that the actual content is correct

**Review by MrCreosote — APPROVED** [review]
*&&*^)&*(^)

**Comment by MrCreosote** [comment]
> I'm relying on Cody to confirm that the actual content is correct

Which he did in Slack

**Pull request merged**
