### PR TITLE
NCBI downloader includes Genomes

### PR DESCRIPTION
**Pull request by Xiangs18**

### CODE REVIEW

**Review by MrCreosote — APPROVED** [review]
Well that was easy

**Comment by MrCreosote** [comment]
actually on second thought - are there tests for this that need to be updated? I think there might be

**Comment by Xiangs18** [comment]
still need approval to merge

**Comment by MrCreosote** [comment]
See comment re tests above

**Review by MrCreosote — COMMENTED** [review]
We'll probably want to add more & better tests in the future but this seems GEFN.

@Tianhao-Gu can you take a look and approve if things look ok?

**Review by Tianhao-Gu — COMMENTED** [review]
It will work. 

There are logic in place to prevent redownloading files in `remove_ids_with_existing_data`. But say if we run the download script for R207 with only `fna.gz` and then run the script for R214 with both `fna.gz` and `gbff.gz`. It will redownload and rewrite all existing `fna.gz` files. 

If that's an ok behavior, this PR looks good to me.

**Comment by Tianhao-Gu** [comment]
> It will work.
> 
> There are logic in place to prevent redownloading files in `remove_ids_with_existing_data`. But say if we run the download script for R207 with only `fna.gz` and then run the script for R214 with both `fna.gz` and `gbff.gz`. It will redownload and rewrite all existing `fna.gz` files.
> 
> If that's an ok behavior, this PR looks good to me.

If we want to prevent redownloading, we need to limit `download_file_ext` to one in order for the avoid redownloading logic to work every time. Otherwise, we need to build logic and figure out target_file_ext for each genome and pass correct input to `download_genome_files` which is the right way to go in my option but involves a lot of refactoring work.

**Comment by MrCreosote** [comment]
Good point. IMO we should make it work correctly and only download missing files rather than redownload the entire directory if any of the required files are missing

**Comment by Xiangs18** [comment]
Not sure what is going on ... but the code only downloads missing files, not the entire directory 
https://github.com/kbase/collections/blob/2727b88ccab4de0ce2d1cd68b90878660bb31936/src/loaders/ncbi_downloader/ncbi_downloader_helper.py#L52

**Comment by Tianhao-Gu** [comment]
> Not sure what is going on ... but the code only downloads missing files, not the entire directory
> 
> https://github.com/kbase/collections/blob/2727b88ccab4de0ce2d1cd68b90878660bb31936/src/loaders/ncbi_downloader/ncbi_downloader_helper.py#L52

I see. In that case, this PR LGTM.

**Review by Tianhao-Gu — APPROVED** [review]

**Comment by Xiangs18** [comment]
@MrCreosote May I also get an approval from you before merging?

**Comment by MrCreosote** [comment]
Tian's is sufficient

**Pull request merged**
