### PR TITLE
add arango class

### PR DESCRIPTION
**Pull request by Tianhao-Gu**

### CODE REVIEW

**Review by MrCreosote — CHANGES_REQUESTED** [review]
This looks fine other than
* Adding a test file that at least imports this file and runs a no-op test so that when we move on from prototyping well see this class needs tests
* Maybe this should go in /common rather than making another directory at the root?

**Comment by MrCreosote** [comment]
Oh, pipfile.lock should be updated as well, missed that

**Comment by MrCreosote** [comment]
I'm sort of wondering now if all the code should just go in `/src` rather than several top level dirs

**Comment by Tianhao-Gu** [comment]
@MrCreosote 👍 addressed comments.

**Review by MrCreosote — APPROVED** [review]
LGTM

**Pull request merged**
